# Generated by Django 4.1.6 on 2023-02-05 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jornal', '0003_alter_artigo_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='autores/'),
        ),
    ]
